uris:
  #- camera-secret:living-room
  - file:///path/to/living-room.mp4
  #- camera-secret:kitchen
  - file:///path/to/kitchen.mp4
  #- camera-secret:family-room
  - file:///path/to/family-room.mp4
sensor_ids:
  - "0"
  - "1"
  - "2"
sensor_names:
  - Living Room Camera
  - Kitchen Camera
  - Family Room Camera
width: 1920
height: 1080
