uris:
  #- rtsp://192.168.3.214:7447/jdr9oLlBkjyl3gDm?
  - file:///home/mayor/Downloads/livingroomclip.mp4
  #- rtsp://192.168.3.214:7447/qt3VqVdZpgG1B4Vk?
  - file:///home/mayor/Downloads/kitchenclip.mp4
  #- rtsp://192.168.3.214:7447/4qWTBhW6b4nLeUFE?
  - file:///home/mayor/Downloads/familyroomclip.mp4
sensor_ids:
  - "0"
  - "1"
  - "2"
sensor_names:
  - Living Room Camera
  - Kitchen Camera
  - Family Room Camera
width: 1920
height: 1080
