[pytest]
testpaths = tests
addopts = --import-mode=importlib
norecursedirs =
    .git
    .venv
    __pycache__
    build
    dist
    external
    node_modules
    runtime
    runtime_ds9
    runtime_ds9_prod
    testpipelines
