// Generated by scripts/export_noesis_core_schemas.py. Do not edit by hand.
// Product contracts are immutable snapshots; unsupported major versions must fail closed.

export type ActionApproval = {
  readonly contract: "noesis.action.approval";
  readonly contract_version: 1;
  readonly approval_id: string;
  readonly action_id: string;
  readonly approver: ActorRef;
  readonly issued_at_us: number;
  readonly expires_at_us: number;
  readonly decision: "approve" | "reject";
  readonly one_use?: true;
};

export type ActionIntent = {
  readonly contract: "noesis.action.intent";
  readonly contract_version: 1;
  readonly action_id: string;
  readonly idempotency_key: string;
  readonly actor: ActorRef;
  readonly capability: string;
  readonly target: string;
  readonly parameters: {
    readonly [key: string]: unknown;
  };
  readonly requested_at_us: number;
  readonly risk: ActionRisk;
  readonly precondition?: {
    readonly [key: string]: unknown;
  } | null;
};

export type ActionRisk = "routine" | "sensitive" | "destructive";

export type ActionStatus = "proposed" | "awaiting_approval" | "executing" | "succeeded" | "failed" | "uncertain" | "rejected";

export type ActorRef = {
  readonly actor_id: string;
  readonly role: ActorRole;
  readonly session_id?: string | null;
};

export type ActorRole = "viewer" | "operator" | "owner" | "agent" | "automation";

export type ApplianceEndpoints = {
  readonly websocket: "ws://127.0.0.1:6008";
  readonly rest: "http://127.0.0.1:8080";
  readonly rtsp: "rtsp://127.0.0.1:8554/ds-test";
};

export type ApplianceReadinessVersions = {
  readonly capability_contract_version: 1;
  readonly deployment_health_contract_version: 1;
  readonly websocket_health_contract_version: 2;
};

export type ArtifactFingerprint = {
  readonly role: string;
  readonly sha256: string;
  readonly version?: string | null;
  readonly producer?: string | null;
};

export type AuditEntry = {
  readonly contract: "noesis.audit.entry";
  readonly contract_version: 1;
  readonly audit_id: string;
  readonly occurred_at_us: number;
  readonly actor: ActorRef;
  readonly event: string;
  readonly action_id?: string | null;
  readonly receipt_id?: string | null;
  readonly redacted_details: {
    readonly [key: string]: unknown;
  };
  readonly previous_entry_sha256?: string | null;
  readonly entry_sha256: string;
};

export type CalibrationAcceptance = {
  readonly passed: true;
  readonly confidence_level: 0.95;
  readonly confidence_method: "clopper_pearson_one_sided";
  readonly max_benchmark_holdout_far_upper_confidence_bound: number;
  readonly max_benchmark_holdout_frr: number;
  readonly max_benchmark_holdout_misidentification_upper_confidence_bound: number;
  readonly max_household_false_accept_encounters: 0;
  readonly max_household_misidentification_encounters: 0;
  readonly max_household_holdout_frr: number;
  readonly max_harmful_prior_encounters: 0;
  readonly max_prior_rejection_rescue_encounters: 0;
  readonly minimum_benchmark_train_known_persons: number;
  readonly minimum_benchmark_train_unknown_persons: number;
  readonly minimum_benchmark_holdout_known_persons: number;
  readonly minimum_benchmark_holdout_unknown_persons: number;
  readonly minimum_household_train_known_encounters: number;
  readonly minimum_household_train_unknown_encounters: number;
  readonly minimum_household_holdout_known_encounters: number;
  readonly minimum_household_holdout_unknown_encounters: number;
};

export type CalibrationCandidateScore = {
  readonly subject_id: string;
  readonly identity_kind: "resident" | "visitor";
  readonly raw_similarity: number;
  readonly hard_allowed?: boolean;
  readonly hard_constraint_reason?: string | null;
  readonly gallery_exemplar_count?: number;
};

export type CalibrationDatasetBinding = {
  readonly evidence_stratum: CalibrationEvidenceStratum;
  readonly dataset_sha256: string;
  readonly evidence_sha256: string;
  readonly labels_sha256: string;
  readonly split_strategy: CalibrationSplitStrategy;
  readonly evidence_sources: ReadonlyArray<CalibrationEvidenceSource>;
  readonly runtimes: ReadonlyArray<string>;
  readonly runtime_modes: ReadonlyArray<string>;
  readonly truth_kinds: ReadonlyArray<CalibrationTruthKind>;
  readonly provenance: CalibrationDatasetProvenance;
  readonly observation_count: number;
  readonly evidence_unit_count: number;
  readonly encounter_count: number;
};

export type CalibrationDatasetProvenance = {
  readonly source_name: string;
  readonly source_revision: string;
  readonly source_manifest_sha256: string;
  readonly model_semantic_profile_sha256: string;
  readonly labeling_protocol_revision: string;
  readonly population_basis: "licensed_real_people" | "owner_consented_household_people";
};

export type CalibrationEvidenceSource = "shadow" | "replay";

export type CalibrationEvidenceStratum = "benchmark" | "household";

export type CalibrationEvidenceUnit = {
  readonly unit_id: string;
  readonly partition: CalibrationPartition;
  readonly truth_kind: CalibrationTruthKind;
  readonly truth_subject_id?: string | null;
  readonly truth_person_key: string;
  readonly encounter_id: string;
  readonly session_id: string;
  readonly run_id: string;
  readonly source: CalibrationEvidenceSource;
  readonly camera_id: string;
  readonly tracker_id: string;
  readonly bucket_index: number;
  readonly event_ids: ReadonlyArray<string>;
  readonly fit_event_id?: string | null;
};

export type CalibrationEvidenceUnitPolicy = {
  readonly algorithm: "session_tracklet_time_bucket_v1";
  readonly bucket_duration_us: 5000000;
  readonly maximum_observations_per_unit: 300;
  readonly fit_thinning: "temporal_cover_center_representative_v1";
  readonly maximum_fit_units_per_encounter: 8;
  readonly fit_representatives_per_unit: 1;
  readonly authority_aggregation: "encounter_worst_case_v1";
};

export type CalibrationFitSummary = {
  readonly score_semantics: "balanced_monotonic_match_score_not_posterior";
  readonly selected_evidence_unit_count: number;
  readonly selected_encounter_count: number;
  readonly selected_person_count: number;
  readonly positive_pair_count: number;
  readonly negative_pair_count: number;
  readonly balanced_log_loss: number;
  readonly balanced_brier_score: number;
  readonly iterations: number;
};

export type CalibrationGalleryLimits = {
  readonly maximum_resident_candidate_count: number;
  readonly maximum_visitor_candidate_count: number;
  readonly maximum_total_candidate_count: number;
  readonly maximum_exemplars_per_candidate: number;
};

export type CalibrationMetrics = {
  readonly confidence_level: 0.95;
  readonly confidence_method: "clopper_pearson_one_sided";
  readonly confidence_unit: "truth_person_worst_case";
  readonly observation_count: number;
  readonly known_observation_count: number;
  readonly unknown_observation_count: number;
  readonly challenge_eligible_observation_count: number;
  readonly evidence_unit_count: number;
  readonly known_evidence_unit_count: number;
  readonly unknown_evidence_unit_count: number;
  readonly encounter_count: number;
  readonly known_encounter_count: number;
  readonly unknown_encounter_count: number;
  readonly challenge_eligible_encounter_count: number;
  readonly correct_accept_encounter_count: number;
  readonly false_reject_encounter_count: number;
  readonly misidentification_encounter_count: number;
  readonly false_accept_encounter_count: number;
  readonly person_count: number;
  readonly known_person_count: number;
  readonly unknown_person_count: number;
  readonly known_challenge_person_count: number;
  readonly unknown_challenge_person_count: number;
  readonly correct_accept_person_count: number;
  readonly false_reject_person_count: number;
  readonly misidentification_person_count: number;
  readonly false_accept_person_count: number;
  readonly misidentification_challenge_person_count: number;
  readonly false_accept_challenge_person_count: number;
  readonly person_far: number;
  readonly person_frr: number;
  readonly person_misidentification_rate: number;
  readonly person_identification_accuracy: number;
  readonly far: number;
  readonly far_upper_confidence_bound: number;
  readonly frr: number;
  readonly frr_upper_confidence_bound: number;
  readonly misidentification_rate: number;
  readonly misidentification_upper_confidence_bound: number;
  readonly unknown_rejection_rate: number;
  readonly identification_accuracy: number;
  readonly resident_prior_changed_encounter_count: number;
  readonly resident_prior_beneficial_encounter_count: number;
  readonly resident_prior_harmful_encounter_count: number;
  readonly resident_prior_rejection_rescue_encounter_count: number;
};

export type CalibrationPartition = "train" | "holdout";

export type CalibrationSplitStrategy = "subject_disjoint" | "session_disjoint";

export type CalibrationTruthKind = "resident" | "visitor" | "unknown";

export type CalibrationTruthLabel = {
  readonly event_id: string;
  readonly partition: CalibrationPartition;
  readonly truth_kind: CalibrationTruthKind;
  readonly truth_subject_id?: string | null;
  readonly truth_person_key: string;
  readonly encounter_id: string;
};

export type CapabilityHealth = {
  readonly contract: "noesis.capability.health";
  readonly contract_version: 1;
  readonly instance_id: string;
  readonly run_id: string;
  readonly generated_at_us: number;
  readonly capabilities: ReadonlyArray<CapabilityState>;
};

export type CapabilityState = {
  readonly capability: string;
  readonly status: CapabilityStatus;
  readonly checked_at_us: number;
  readonly last_success_at_us?: number | null;
  readonly evidence: {
    readonly [key: string]: unknown;
  };
  readonly blockers?: ReadonlyArray<string>;
};

export type CapabilityStatus = "healthy" | "degraded" | "failed" | "blocked" | "unknown";

export type CheckoutBinding = {
  readonly root: string;
  readonly snapshot_kind: "menon-runtime-v1" | "noesis-runtime-v1";
  readonly snapshot_sha256: string;
  readonly software_revision: string;
};

export type DS9RuntimeSelector = {
  readonly family: "ds9";
  readonly lane: "baseline" | "v3dt" | "wholebody49-s" | "wholebody49-x";
  readonly supervisor_path: string;
  readonly native_root: string;
  readonly artifact_root: string;
  readonly runtime_root: string;
  readonly asset_realization_sha256: string;
  readonly ownership_matrix_sha256: string;
};

export type DeploymentHealth = {
  readonly contract: "noesis.appliance.deployment_health";
  readonly contract_version: 1;
  readonly deployment_id: string;
  readonly selector_sha256: string;
  readonly state_release_id: string;
  readonly runtime_family: "ds9";
  readonly runtime_variant: string;
  readonly instance_id: string;
  readonly run_id: string;
  readonly boot_id: string;
  readonly software_revision: string;
  readonly generated_at_us: number;
  readonly ready: true;
};

export type DeploymentSelector = {
  readonly contract: "noesis.appliance.deployment_selector";
  readonly contract_version: 1;
  readonly deployment_id: string;
  readonly created_at: string;
  readonly bundle_sha256: string;
  readonly menon_checkout: CheckoutBinding;
  readonly noesis_checkout: CheckoutBinding;
  readonly state_release: StateReleaseBinding;
  readonly endpoints: ApplianceEndpoints;
  readonly runtime: DS9RuntimeSelector;
  readonly readiness: ApplianceReadinessVersions;
};

export type EntityLifecycle = "present" | "held" | "lost";

export type ExecutionReceipt = {
  readonly contract: "noesis.action.receipt";
  readonly contract_version: 1;
  readonly receipt_id: string;
  readonly action_id: string;
  readonly status: ActionStatus;
  readonly started_at_us: number;
  readonly completed_at_us: number;
  readonly provider: string;
  readonly provider_result?: {
    readonly [key: string]: unknown;
  } | null;
  readonly readback?: {
    readonly [key: string]: unknown;
  } | null;
  readonly error?: string | null;
};

export type IdentityAuthorityCutoverArtifact = {
  readonly contract: "noesis.identity.authority_cutover";
  readonly contract_version: 1;
  readonly approved_at_us: number;
  readonly approved_by: string;
  readonly runtime: "ds9";
  readonly model_sha256: string;
  readonly model_layer: string;
  readonly embedding_dim: number;
  readonly model_semantic_profile_sha256: string;
  readonly scoring_artifact_sha256: string;
  readonly authority_runtime_profile_sha256: string;
  readonly camera_topology_sha256: string;
  readonly camera_ids: ReadonlyArray<string>;
  readonly authority_scope: "full_identity_runtime_public_cutover";
  readonly coordinator_replay: IdentityAuthorityGateEvidence;
  readonly occupied_scene: IdentityAuthorityGateEvidence;
};

export type IdentityAuthorityGateEvidence = {
  readonly evidence_kind: "whole_frame_coordinator_replay" | "occupied_scene_runtime";
  readonly evidence_path: string;
  readonly evidence_sha256: string;
  readonly evidence_size_bytes: number;
  readonly evidence_revision: string;
  readonly completed_at_us: number;
  readonly passed: true;
};

export type IdentityCalibrationDataset = {
  readonly contract: "noesis.identity.calibration_dataset";
  readonly contract_version: 2;
  readonly evidence_sha256: string;
  readonly labels_sha256: string;
  readonly evidence_stratum: CalibrationEvidenceStratum;
  readonly split_strategy: CalibrationSplitStrategy;
  readonly provenance: CalibrationDatasetProvenance;
  readonly labeled_by: string;
  readonly labeling_revision: string;
  readonly model_sha256: string;
  readonly model_layer: string;
  readonly embedding_dim: number;
  readonly evidence_chain: IdentityEvidenceChainCheckpoint;
  readonly evidence_unit_policy: CalibrationEvidenceUnitPolicy;
  readonly samples: ReadonlyArray<LabeledCalibrationSample>;
  readonly evidence_units: ReadonlyArray<CalibrationEvidenceUnit>;
};

export type IdentityDecision = {
  readonly contract: "noesis.identity.decision";
  readonly contract_version: 1;
  readonly decision_id: string;
  readonly tracklets: ReadonlyArray<TrackletRef>;
  readonly outcome: IdentityOutcome;
  readonly subject?: SubjectRef | null;
  readonly decided_at_us: number;
  readonly evidence: IdentityEvidenceSummary;
  readonly required_similarity?: number | null;
  readonly absolute_open_set_floor?: number | null;
  readonly reject_reason?: string | null;
  readonly prior_changed_winner?: boolean;
  readonly overlap_permit?: boolean;
};

export type IdentityEvidenceChainCheckpoint = {
  readonly contract: "noesis.identity.shadow_score_evidence_chain";
  readonly contract_version: 1;
  readonly next_sequence: number;
  readonly first_sequence?: number | null;
  readonly previous_event_id?: string | null;
  readonly tail_event_id?: string | null;
  readonly retained_count: number;
  readonly retained_bytes: number;
  readonly updated_at_us: number;
  readonly checkpoint_sha256: string;
};

export type IdentityEvidenceLabelSet = {
  readonly contract: "noesis.identity.evidence_labels";
  readonly contract_version: 2;
  readonly evidence_sha256: string;
  readonly evidence_stratum: CalibrationEvidenceStratum;
  readonly split_strategy: CalibrationSplitStrategy;
  readonly provenance: CalibrationDatasetProvenance;
  readonly labeled_by: string;
  readonly labeling_revision: string;
  readonly labels: ReadonlyArray<CalibrationTruthLabel>;
};

export type IdentityEvidenceSummary = {
  readonly embedding_present: boolean;
  readonly embedding_sequence?: number | null;
  readonly embedding_model_sha256?: string | null;
  readonly embedding_dimension?: number | null;
  readonly appearance_similarity?: number | null;
  readonly calibrated_confidence?: number | null;
  readonly ambiguity_margin?: number | null;
  readonly prior_contribution?: number;
  readonly independent_observation_count?: number;
  readonly pose_present?: boolean;
  readonly world_present?: boolean;
  readonly quality_accepted?: boolean;
};

export type IdentityKind = "resident" | "visitor" | "unknown" | "provisional";

export type IdentityOpenSetCalibrationArtifact = {
  readonly contract: "noesis.identity.open_set_calibration";
  readonly contract_version: 2;
  readonly generated_at_us: number;
  readonly generator: "scripts/identity_v2_calibrate.py";
  readonly generator_revision: string;
  readonly model_sha256: string;
  readonly model_layer: string;
  readonly embedding_dim: number;
  readonly model_semantic_profile_sha256: string;
  readonly authority_scope: "open_set_scorer_policy_only";
  readonly gallery_limits: CalibrationGalleryLimits;
  readonly evidence_unit_policy: CalibrationEvidenceUnitPolicy;
  readonly benchmark_dataset: CalibrationDatasetBinding;
  readonly household_dataset: CalibrationDatasetBinding;
  readonly benchmark_policy: IdentityOpenSetPolicyContract;
  readonly policy: IdentityOpenSetPolicyContract;
  readonly fit: CalibrationFitSummary;
  readonly benchmark_training_metrics: CalibrationMetrics;
  readonly benchmark_holdout_metrics: CalibrationMetrics;
  readonly household_training_metrics: CalibrationMetrics;
  readonly household_holdout_metrics: CalibrationMetrics;
  readonly acceptance: CalibrationAcceptance;
};

export type IdentityOpenSetPolicyContract = {
  readonly appearance_floor: number;
  readonly quality_floor: number;
  readonly calibrated_confidence_floor: number;
  readonly ambiguity_margin_floor: number;
  readonly calibration_slope: number;
  readonly calibration_midpoint: number;
  readonly resident_prior_bonus: number;
  readonly resident_prior_cap: number;
  readonly unknown_utility: number;
};

export type IdentityOutcome = "resident" | "visitor" | "unknown";

export type LabeledCalibrationSample = {
  readonly evidence: ShadowIdentityEvidenceRecord;
  readonly label: CalibrationTruthLabel;
};

export type Matrix3 = {
  readonly values: readonly [number, number, number, number, number, number, number, number, number];
};

export type ObservationEnvelope = {
  readonly contract: "noesis.observation.person";
  readonly contract_version: 1;
  readonly observation_id: string;
  readonly producer: ProducerRef;
  readonly sequence: number;
  readonly captured_at_us?: number | null;
  readonly observed_at_us: number;
  readonly published_at_us: number;
  readonly capture_time_status: "synced" | "estimated" | "unavailable";
  readonly media_pts_ns?: number | null;
  readonly coordinate_frame: "backend_world_m" | "camera_local_ground_m" | "image_px";
  readonly units: "meters" | "pixels";
  readonly calibration: ArtifactFingerprint;
  readonly model: ArtifactFingerprint;
  readonly config: ArtifactFingerprint;
  readonly payload: PersonObservation;
};

export type PersonObservation = {
  readonly tracklet: TrackletRef;
  readonly class_id?: 0;
  readonly detection_confidence?: number | null;
  readonly tracker_confidence?: number | null;
  readonly bbox_xywh: readonly [number, number, number, number];
  readonly image_size: readonly [number, number];
  readonly zone?: string | null;
  readonly zone_source?: "nvdsanalytics_roi" | "camera_default" | null;
  readonly zone_authoritative?: boolean;
  readonly world?: WorldPositionObservation | null;
  readonly world_diagnostics?: WorldObservationDiagnostics | null;
  readonly embedding_sequence?: number | null;
  readonly embedding_model_sha256?: string | null;
  readonly embedding_dimension?: number | null;
  readonly pose_present?: boolean;
  readonly depth_present?: boolean;
  readonly occluded?: boolean;
};

export type ProducerRef = {
  readonly runtime: "ds8" | "ds9" | "replay" | "test";
  readonly instance_id: string;
  readonly run_id: string;
  readonly software_revision: string;
};

export type RuntimeDeploymentContext = {
  readonly contract: "noesis.appliance.runtime_context";
  readonly contract_version: 1;
  readonly deployment_id: string;
  readonly selector_sha256: string;
  readonly state_release_id: string;
  readonly runtime_family: "ds9";
  readonly runtime_variant: string;
  readonly boot_id: string;
  readonly software_revision: string;
};

export type SceneArtifact = {
  readonly role: string;
  readonly relative_path: string;
  readonly sha256: string;
  readonly size_bytes: number;
};

export type SceneCameraRevision = {
  readonly camera_id: string;
  readonly revision_id: string;
  readonly captured_at_us: number;
  readonly calibration_bundle_sha256: string;
  readonly calibration_sha256: string;
  readonly model_bundle_sha256: string;
  readonly model_sha256: string;
  readonly manifest_sha256: string;
  readonly artifact_path: string;
  readonly artifacts: ReadonlyArray<SceneArtifact>;
};

export type ScenePriorArtifact = {
  readonly role: string;
  readonly relative_path: string;
  readonly sha256: string;
  readonly size_bytes: number;
};

export type ScenePriorBounds = {
  readonly min_x: number;
  readonly max_x: number;
  readonly min_z: number;
  readonly max_z: number;
};

export type ScenePriorCameraBinding = {
  readonly camera_id: string;
  readonly space_id: string;
  readonly prior_id: string;
  readonly mode: "shadow";
  readonly include_floorplan_layers?: boolean;
  readonly frame_binding?: ScenePriorFrameBinding | null;
};

export type ScenePriorCatalog = {
  readonly contract: "noesis.scene_prior.catalog";
  readonly contract_version: 1;
  readonly site_id: string;
  readonly revisions: ReadonlyArray<ScenePriorCatalogEntry>;
  readonly camera_bindings: ReadonlyArray<ScenePriorCameraBinding>;
};

export type ScenePriorCatalogEntry = {
  readonly prior_id: string;
  readonly space_id: string;
  readonly manifest_path: string;
  readonly manifest_sha256: string;
  readonly manifest_size_bytes: number;
};

export type ScenePriorDerivation = {
  readonly algorithm: "noesis_scene_prior_2_5d_v1" | "noesis_scene_prior_2_5d_full_evidence_v2";
  readonly floor_y_m: number;
  readonly floor_support_band_m: number;
  readonly obstacle_min_height_m: number;
  readonly obstacle_max_height_m: number;
  readonly obstacle_min_support: number;
  readonly max_source_height_m: number;
};

export type ScenePriorFloorPlane = {
  readonly frame: ScenePriorFrameRef;
  readonly normal: readonly [number, number, number];
  readonly offset_m: number;
};

export type ScenePriorFrameBinding = {
  readonly contract: "noesis.scene_prior.frame_binding";
  readonly contract_version: 1;
  readonly source_frame: ScenePriorFrameRef;
  readonly target_frame: ScenePriorFrameRef;
  readonly source_camera_calibration_sha256: string;
  readonly source_world_alignment_sha256: string;
  readonly target_revision_id: string;
  readonly target_revision_metadata_sha256: string;
  readonly target_from_source_col_major: ReadonlyArray<number>;
  readonly target_from_source_sha256: string;
  readonly source_floor_plane: ScenePriorFloorPlane;
  readonly target_floor_plane: ScenePriorFloorPlane;
};

export type ScenePriorFrameRef = {
  readonly frame_id: "backend_world_m";
  readonly revision: string;
};

export type ScenePriorGrid = {
  readonly coordinate_frame: "backend_world_m";
  readonly units: "meters";
  readonly orientation: "row_increases_positive_z_column_increases_positive_x";
  readonly bounds: ScenePriorBounds;
  readonly resolution_m: number;
  readonly rows: number;
  readonly columns: number;
};

export type ScenePriorPreview = {
  readonly coordinate_frame: "camera_local_ground_m";
  readonly units: "meters";
  readonly orientation: "row_zero_max_z_rows_toward_min_z_columns_min_x_to_max_x" | "row_increases_camera_forward_column_increases_camera_right";
  readonly reference_camera_id: string;
  readonly camera_calibration: ArtifactFingerprint;
  readonly target_revision_metadata: ArtifactFingerprint;
  readonly camera_position_world_m: readonly [number, number, number];
  readonly camera_right_world_xz: readonly [number, number];
  readonly camera_forward_world_xz: readonly [number, number];
  readonly bounds: ScenePriorBounds;
  readonly resolution_m: number;
  readonly rows: number;
  readonly columns: number;
};

export type ScenePriorQuality = {
  readonly passed: boolean;
  readonly source_point_count: number;
  readonly selected_point_count: number;
  readonly authored_cell_count: number;
  readonly observed_cell_count: number;
  readonly floor_supported_cell_count: number;
  readonly obstacle_cell_count: number;
  readonly authored_observed_fraction: number;
  readonly authored_floor_supported_fraction: number;
  readonly alignment_status: string;
};

export type ScenePriorRevision = {
  readonly contract: "noesis.scene_prior.revision";
  readonly contract_version: 1;
  readonly prior_id: string;
  readonly site_id: string;
  readonly space_id: string;
  readonly created_at_us: number;
  readonly created_by: string;
  readonly intended_use: "shadow";
  readonly source: ScenePriorSource;
  readonly alignment: ArtifactFingerprint;
  readonly authored_scene: ArtifactFingerprint;
  readonly world_to_scene: ArtifactFingerprint;
  readonly semantic_binding: ScenePriorSemanticBinding;
  readonly grid: ScenePriorGrid;
  readonly preview?: ScenePriorPreview | null;
  readonly derivation: ScenePriorDerivation;
  readonly quality: ScenePriorQuality;
  readonly artifacts: ReadonlyArray<ScenePriorArtifact>;
};

export type ScenePriorSemanticBinding = {
  readonly room_labels: ReadonlyArray<string>;
  readonly authored_groups: ReadonlyArray<string>;
  readonly room_group_map: ArtifactFingerprint;
};

export type ScenePriorSource = {
  readonly source_type: "mapanything_multiview_room_walk" | "conditioned_multimodel_room_walk";
  readonly bundle_id: string;
  readonly bundle_schema: string;
  readonly bundle_manifest_sha256: string;
  readonly reference_sha256: string;
  readonly capture_id: string;
  readonly captured_at_us: number;
  readonly model: string;
};

export type SceneRelease = {
  readonly contract: "noesis.scene.release";
  readonly contract_version: 1;
  readonly release_id: string;
  readonly release_version: 1;
  readonly created_at_us: number;
  readonly created_by: string;
  readonly calibration: ArtifactFingerprint;
  readonly model: ArtifactFingerprint;
  readonly config: ArtifactFingerprint;
  readonly authored_scene: ArtifactFingerprint;
  readonly authored_scene_path: string;
  readonly authored_scene_size_bytes: number;
  readonly authored_scene_dependencies: ReadonlyArray<SceneArtifact>;
  readonly cohort_max_delta_us: number;
  readonly cameras: ReadonlyArray<SceneCameraRevision>;
  readonly validation_report_sha256: string;
  readonly validation_report_path: string;
  readonly validation_report_size_bytes: number;
};

export type ShadowIdentityEvidenceRecord = {
  readonly contract: "noesis.identity.shadow_score_evidence";
  readonly contract_version: 2;
  readonly event_id: string;
  readonly sequence: number;
  readonly previous_event_id?: string | null;
  readonly observed_at_us: number;
  readonly source: CalibrationEvidenceSource;
  readonly session_id: string;
  readonly runtime: "ds8" | "ds9" | "replay" | "test";
  readonly runtime_mode: "shadow" | "authoritative";
  readonly run_id: string;
  readonly camera_id: string;
  readonly tracker_id: string;
  readonly frame_id: number;
  readonly observation_id: string;
  readonly model_sha256: string;
  readonly model_semantic_profile_sha256: string;
  readonly model_layer: string;
  readonly embedding_dim: number;
  readonly quality: number;
  readonly candidates: ReadonlyArray<CalibrationCandidateScore>;
  readonly pre_prior_winner_id?: string | null;
  readonly final_winner_id?: string | null;
  readonly final_outcome: "resident" | "visitor" | "unknown";
  readonly calibrated_confidence: number;
  readonly reject_reason?: string | null;
  readonly prior_changed_winner?: boolean;
};

export type StateBaseline = {
  readonly contract: "noesis.appliance.state_baseline";
  readonly contract_version: 1;
  readonly release_id: string;
  readonly created_at: string;
  readonly files: {
    readonly [key: string]: StateBaselineFile;
  };
};

export type StateBaselineBinding = {
  readonly inventory_path: string;
  readonly inventory_sha256: string;
  readonly file_count: number;
  readonly byte_count: number;
};

export type StateBaselineFile = {
  readonly sha256: string;
  readonly bytes: number;
};

export type StateMigration = {
  readonly mode: "fresh" | "clone" | "migrate";
  readonly tool_sha256: string;
  readonly report_sha256: string;
};

export type StateRelease = {
  readonly contract: "noesis.appliance.state_release";
  readonly contract_version: 1;
  readonly release_id: string;
  readonly parent_release_id: string | null;
  readonly created_at: string;
  readonly root: string;
  readonly schemas: {
    readonly [key: string]: number;
  };
  readonly migration: StateMigration;
  readonly baseline: StateBaselineBinding;
};

export type StateReleaseBinding = {
  readonly release_id: string;
  readonly manifest_path: string;
  readonly manifest_sha256: string;
};

export type SubjectRef = {
  readonly subject_id: string;
  readonly kind: IdentityKind;
  readonly generation?: number;
  readonly resident_uuid?: string | null;
  readonly display_name?: string | null;
  readonly stable_id?: number | null;
};

export type TrackletRef = {
  readonly run_id: string;
  readonly camera_id: string;
  readonly source_id: number;
  readonly tracker_id: number;
  readonly frame_id: number;
  readonly observed_at_us: number;
};

export type Vector3 = {
  readonly x: number;
  readonly y: number;
  readonly z: number;
};

export type WebSocketDeploymentHealth = {
  readonly type: "health";
  readonly contract: "noesis.ws.health";
  readonly contract_version: 2;
  readonly deployment_id: string;
  readonly selector_sha256: string;
  readonly state_release_id: string;
  readonly runtime_family: "ds9";
  readonly runtime_variant: string;
  readonly instance_id: string;
  readonly run_id: string;
  readonly boot_id: string;
  readonly software_revision: string;
  readonly generated_at_us: number;
  readonly ready: true;
};

export type WorldEntity = {
  readonly entity_id: string;
  readonly subject: SubjectRef;
  readonly lifecycle: EntityLifecycle;
  readonly position?: Vector3 | null;
  readonly covariance?: Matrix3 | null;
  readonly world_frame?: "backend_world_m";
  readonly world_frame_revision?: string | null;
  readonly world_transform_sha256?: string | null;
  readonly calibration_revision?: string | null;
  readonly position_quantity?: "ground_footprint";
  readonly support_state?: "floor" | "seat" | "couch" | "unknown";
  readonly posture?: "standing" | "sitting" | "lying" | "unknown";
  readonly velocity_mps?: Vector3 | null;
  readonly room_id?: string | null;
  readonly observed_at_us: number;
  readonly stale_after_us: number;
  readonly sources: ReadonlyArray<WorldSourceEvidence>;
  readonly conflict?: boolean;
  readonly conflict_reason?: string | null;
};

export type WorldEvent = {
  readonly contract: "noesis.world.event";
  readonly contract_version: 1;
  readonly event_id: string;
  readonly producer: ProducerRef;
  readonly sequence: number;
  readonly event_type: "appeared" | "held" | "resumed" | "lost" | "conflict_started" | "conflict_cleared";
  readonly entity_id: string;
  readonly subject: SubjectRef;
  readonly observed_at_us: number;
  readonly published_at_us: number;
  readonly frame: "backend_world_m";
  readonly units: "meters";
  readonly world_frame?: "backend_world_m";
  readonly world_frame_revision?: string | null;
  readonly world_transform_sha256?: string | null;
  readonly calibration_revision?: string | null;
  readonly position?: Vector3 | null;
  readonly reason?: string | null;
};

export type WorldMeasurementCandidateDiagnostic = {
  readonly candidate_id: string;
  readonly kind: "floor_ray" | "registered_depth" | "pose_scale" | "gravity_reconstruction";
  readonly score: number;
  readonly pcf_score: number;
  readonly innovation_m?: number | null;
  readonly agreement_mahalanobis_sq?: number | null;
  readonly compatible_with_selected?: boolean;
  readonly selected?: boolean;
  readonly retained_as_alternate?: boolean;
  readonly rejection_reason?: string | null;
};

export type WorldObservationDiagnostics = {
  readonly estimator_evaluated?: boolean | null;
  readonly first_divergence_reason?: string | null;
  readonly floor_candidate_m?: Vector3 | null;
  readonly depth_candidate_m?: Vector3 | null;
  readonly prefilter_measurement_m?: Vector3 | null;
  readonly filter_prediction_m?: Vector3 | null;
  readonly floor_range_m?: number | null;
  readonly floor_range_limit_m?: number | null;
  readonly floor_incidence_sin?: number | null;
  readonly floor_admitted?: boolean | null;
  readonly floor_rejection_reason?: string | null;
  readonly measurement_accepted?: boolean | null;
  readonly measurement_rejection_reason?: string | null;
  readonly innovation_m?: number | null;
  readonly innovation_limit_m?: number | null;
  readonly fusion_policy_id?: string | null;
  readonly floor_weight_scale?: number | null;
  readonly depth_weight_scale?: number | null;
  readonly floor_weight_effective?: number | null;
  readonly depth_weight_effective?: number | null;
  readonly depth_status?: string | null;
  readonly depth_anchor_m?: number | null;
  readonly depth_registered_m?: number | null;
  readonly depth_used_m?: number | null;
  readonly depth_registration_status?: string | null;
  readonly depth_registration_id?: string | null;
  readonly resolver_selected_kind?: "floor_ray" | "registered_depth" | "pose_scale" | "gravity_reconstruction" | null;
  readonly resolver_selected_candidate_id?: string | null;
  readonly resolver_contributor_ids?: ReadonlyArray<string>;
  readonly resolver_alternate_candidate_id?: string | null;
  readonly resolver_fused?: boolean | null;
  readonly resolver_confidence?: number | null;
  readonly resolver_disagreement_m?: number | null;
  readonly resolver_agreement_mahalanobis_sq?: number | null;
  readonly resolver_pcf_score?: number | null;
  readonly resolver_reason?: string | null;
  readonly resolver_candidate_diagnostics?: ReadonlyArray<WorldMeasurementCandidateDiagnostic>;
};

export type WorldPositionObservation = {
  readonly position: Vector3;
  readonly covariance: Matrix3;
  readonly frame?: "backend_world_m";
  readonly world_frame?: "backend_world_m";
  readonly units?: "meters";
  readonly world_frame_revision?: string | null;
  readonly world_transform_sha256?: string | null;
  readonly calibration_revision?: string | null;
  readonly quantity?: "ground_footprint";
  readonly support_state?: "floor" | "seat" | "couch" | "unknown";
  readonly posture?: "standing" | "sitting" | "lying" | "unknown";
  readonly source: string;
  readonly quality: "good" | "estimated" | "held";
  readonly confidence: number;
  readonly reason?: string | null;
};

export type WorldSnapshot = {
  readonly contract: "noesis.world.snapshot";
  readonly contract_version: 1;
  readonly snapshot_id: string;
  readonly producer: ProducerRef;
  readonly sequence: number;
  readonly observed_start_us: number;
  readonly observed_end_us: number;
  readonly published_at_us: number;
  readonly frame: "backend_world_m";
  readonly units: "meters";
  readonly entities: ReadonlyArray<WorldEntity>;
};

export type WorldSourceEvidence = {
  readonly observation_id: string;
  readonly camera_id: string;
  readonly zone?: string | null;
  readonly zone_source?: "nvdsanalytics_roi" | "camera_default" | null;
  readonly zone_authoritative?: boolean;
  readonly observed_at_us: number;
  readonly position: Vector3;
  readonly covariance: Matrix3;
  readonly world_frame?: "backend_world_m";
  readonly world_frame_revision?: string | null;
  readonly world_transform_sha256?: string | null;
  readonly calibration_revision?: string | null;
  readonly accepted: boolean;
  readonly rejection_reason?: string | null;
};
