%YAML:1.0
################################################################################
# NVIDIA DeepStream NvDCF Tracker Configuration - Advanced Batch Processing
# Optimized for multi-stream batch processing with proper sub-batch handling
################################################################################

# Main tracker configuration
tracker:
  tracker-width: 640
  tracker-height: 640
  gpu-id: 0
  ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
  ll-config-file: config_tracker_nvdcf_batch_lowlevel.yml
  tracking-id-reset-mode: 0
  # 0: Never reset tracking ID
  # 1: Reset tracking ID when stream restarts
  # 2: Reset tracking ID based on time

# Batch processing configuration
batch_config:
  enable_batch_processing: 1
  max_batch_size: 4
  sub_batch_size: 1
  batch_timeout_ms: 100
  enable_sub_batch_processing: 1

# NvDCF-specific parameters optimized for batch processing
NvDCF:
  # Feature extraction parameters
  useColorNames: 1
  useHog: 0
  useHist: 1
  
  # Tracker parameters
  maxMatchingFrameGap: 5
  maxTrackingFrameGap: 15
  stateEstimatorType: 1  # 0: Dummy, 1: Simple
  
  # Visual tracker parameters
  visualTrackerType: 1  # 0: Dummy, 1: NvDCF
  
  # Data association parameters
  dataAssociatorType: 0  # 0: Default
  associationMatcherType: 0  # 0: Bipartite, 1: Greedy
  
  # Matching thresholds
  matchingThresholdLocal: 0.7
  matchingThresholdGlobal: 0.2
  
  # State estimator parameters
  processNoiseVar4Loc: 2.0
  processNoiseVar4Size: 1.0
  processNoiseVar4Vel: 0.1
  measurementNoiseVar4Detector: 4.0
  measurementNoiseVar4Tracker: 16.0
  
  # DCF parameters
  featureImgSizeLevel: 3
  featureFocusOffsetFactor_y: -0.1
  featureFocusOffsetFactor_x: 0.0
  templateUpdateInterval: 5
  searchRegionPaddingScale: 3.0
  
  # Correlation filter parameters
  filterLr: 0.075
  filterChannelWeightsLr: 0.015
  gaussianSigma: 0.75
  
  # Re-ID parameters (if using appearance features)
  useReidFeature: 0
  reidFeatureSize: 128
  reidHistorySize: 100
  
  # Track management
  minTrackerConfidence: 0.6
  minTargetBboxSize: 10
  minDetectorConfidence: 0.0
  
  # Track termination
  targetVisibilityThreshold: 0.1
  trackExponentialSmoothingLr_loc: 0.5
  trackExponentialSmoothingLr_scale: 0.3
  trackExponentialSmoothingLr_velocity: 0.05
  locUncertaintyThreshold: 50.0

# Sub-batch configuration for each stream
sub_batches:
  0:  # Sub-batch 0 configuration
    ll-config-file: config_tracker_nvdcf_batch_lowlevel.yml
    enable_batch_processing: 1
    max_targets_per_sub_batch: 50
    sub_batch_timeout_ms: 50 