[property]
gpu-id=0
#net-scale-factor=0.0039215697906911373
custom-lib-path=/opt/nvidia/deepstream/deepstream/lib/libnvdsparsebbox_yolo11.so
onnx-file=/home/mayor/Noesis_Devel/models/yolo11m.onnx
model-engine-file=/home/mayor/Noesis_Devel/models/engines/yolo11m_fp16.engine
labelfile-path=/home/mayor/Noesis_Devel/models/coco_labels.txt
batch-size=3
cluster-mode=2
interval=1
gie-unique-id=1
maintain-aspect-ratio=1
network-mode=2
symmetric-padding=1
model-color-format=0
#input-tensor-from-meta=1
# Enable output tensors so NvDsInferTensorMeta is attached (NVDSINFER_TENSOR_OUTPUT_META=12)
input-tensor-from-meta=1
output-tensor-meta=0
network-type=0
# COCO classes
num-detected-classes=80
operate-on-class-ids=0
process-mode=1
parse-bbox-func-name=NvDsInferParseYolo

[class-attrs-all]
pre-cluster-threshold=0.99
topk=300

[class-attrs-0]
pre-cluster-threshold=0.25
