[property]
enable=1
gpu-id=0
unique-id=21
process-on-frame=0
target-unique-ids=22
operate-on-gie-id=1
batch-size=3
network-input-order=0
processing-width=518
processing-height=518
network-input-shape=3;12;518;518
network-color-format=0
tensor-data-type=0
tensor-name=mapanything_fused
tensor-buf-pool-size=12
scaling-buf-pool-size=12
maintain-aspect-ratio=0
symmetric-padding=0
scaling-pool-memory-type=2
scaling-filter=1
custom-lib-path=/home/mayor/Noesis_Devel/pipelines/mapanything_preprocess_fused/libmapanything_preprocess_fused.so
custom-tensor-preparation-function=CustomTensorPreparation

[user-configs]
intrinsics-table=/home/mayor/Noesis_Devel/models/mapanything_depth/intrinsics_table.txt
pixel-normalization-factor=0.0039215688593684392

[group-0]
src-ids=-1
# Operate on person class (0) from PGIE; set to desired classes
operate-on-class-ids=0
process-on-all-objects=1
# Allow all object sizes
input-object-min-width=1
input-object-min-height=1
