%YAML:1.0
################################################################################
# DS8 tracker configuration wrapper (pipeline-level settings)
################################################################################

tracker:
  tracker-width: 640
  tracker-height: 640
  gpu-id: 0
  display-tracking-id: 0
  tracking-id-reset-mode: 0
  ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
  ll-config-file: ../config/nvtracker.yaml
