################################################################################
# Noesis DS8 multi-URI source configuration (modeled after deepstream-test5)
################################################################################

[source-list]
# Use nvmultiurisrcbin and statically seed initial sources
use-nvmultiurisrcbin=1
num-source-bins=3
list=rtsp://192.168.3.214:7447/jdr9oLlBkjyl3gDm?;rtsp://192.168.3.214:7447/qt3VqVdZpgG1B4Vk?;rtsp://192.168.3.214:7447/4qWTBhW6b4nLeUFE?
sensor-id-list=0;1;2
sensor-name-list=Living-Room;Kitchen;Family-Room;
max-batch-size=4
http-ip=localhost
http-port=9000
stream-name-display=0

[source-attr-all]
enable=1
type=3
num-sources=3
gpu-id=0
cudadec-memtype=0
sensorID-padID-mapping=0
latency=5000
select-rtp-protocol=4
rtsp-reconnect-interval-sec=10
init-rtsp-reconnect-interval-sec=5
rtsp-reconnect-attempts=4

[streammux]
gpu-id=0
batch-size=3
batched-push-timeout=33333
width=1920
height=1080
enable-padding=0
nvbuf-memory-type=0
drop-pipeline-eos=1
live-source=1
cache-buffer=0
sort-batch=0
align-first-buffer=0

