################################################################################
# Noesis DS8 multi-URI source configuration (modeled after deepstream-test5)
################################################################################

[source-list]
# Use nvmultiurisrcbin and statically seed initial sources
use-nvmultiurisrcbin=1
max-batch-size=3
http-ip=localhost
list=rtsp://192.168.3.214:7447/jdr9oLlBkjyl3gDm?;rtsp://192.168.3.214:7447/4qWTBhW6b4nLeUFE?;rtsp://192.168.3.214:7447/qt3VqVdZpgG1B4Vk?
#file:///home/mayor/Downloads/kitchenclip.mp4; rtsp://192.168.3.214:7447/qt3VqVdZpgG1B4Vk?
http-port=9010
# Enable internal REST API for multi-URI management (non-zero to enable)#
stream-name-display=0

[source-attr-all]
enable=1
type=3
gpu-id=0
cudadec-memtype=0
sensorID-padID-mapping=0
latency=100
select-rtp-protocol=4
rtsp-reconnect-interval-sec=10
init-rtsp-reconnect-interval-sec=5
rtsp-reconnect-attempts=4

[streammux]
sync-inputs=0
batch-size=3
batched-push-timeout=40000
enable-padding=1
nvbuf-memory-type=0
drop-pipeline-eos=1
cache-buffer=0
sort-batch=0
align-first-buffer=0

