version: 1

intrinsics_models:
  unifi_g3_instant:
    intrinsics:
      fx: 656.10
      fy: 956.39
      cx: 960.00
      cy: 540.00
      k1: 0.0
      k2: 0.0
      k3: 0.0
  unifi_g4_instant:
    intrinsics:
      fx: 514.00
      fy: 692.50
      cx: 640.00
      cy: 360.00
      k1: 0.0
      k2: 0.0
      k3: 0.0
  unifi_g3_bullet:
    intrinsics:
      fx: 1321.33
      fy: 1370.87
      cx: 960.00
      cy: 540.00
      k1: 0.0
      k2: 0.0
      k3: 0.0

cameras:
  0:
    name: living-room
    model: unifi_g3_instant
    height_m: 2.6
  1:
    name: kitchen
    model: unifi_g3_instant
    height_m: 2.7
  2:
    name: family-room
    model: unifi_g4_instant
    height_m: 1.5