[property]
# RF-DETR instance segmentation primary detector for DeepStream 9.
onnx-file=@ONNX_PATH@
model-engine-file=@ENGINE_PATH@
labelfile-path=../models/coco_labels.txt

gpu-id=0
batch-size=3
interval=0
gie-unique-id=1
process-mode=1
network-type=3
network-mode=2
net-scale-factor=0.003921568627
model-color-format=0
maintain-aspect-ratio=1
symmetric-padding=1
disable-output-host-copy=0
cluster-mode=4

num-detected-classes=80
operate-on-class-ids=0

parse-bbox-instance-mask-func-name=NvDsInferParseRFDETRSeg
custom-lib-path=nvdsinfer_rfdetr_seg/libnvdsinfer_rfdetr_seg.so
output-instance-mask=1
output-blob-names=dets;labels;masks
segmentation-threshold=0.50
output-tensor-meta=0

[class-attrs-all]
pre-cluster-threshold=0.99
topk=@TOPK@
nms-iou-threshold=0.45

[class-attrs-0]
pre-cluster-threshold=0.4
