[property]
# YOLO26 pose SGIE for DeepStream 9.
gpu-id=0
onnx-file=DS9/models/onnx/yolo26n-pose.onnx
model-engine-file=DS9/models/engines/yolo26n-pose_b16_fp16.engine
labelfile-path=../../testpipelines/yolo26-pose/labels.txt

batch-size=16
network-mode=2
process-mode=2
network-type=100
gie-unique-id=4
classifier-async-mode=0
net-scale-factor=0.003921568627
model-color-format=0
infer-dims=3;640;640
maintain-aspect-ratio=1
symmetric-padding=1
scaling-filter=1
output-blob-names=output0
output-tensor-meta=1
disable-output-host-copy=0

operate-on-gie-id=1
operate-on-class-ids=0
input-object-min-width=64
input-object-min-height=64
