[property]
# YOLO11 instance segmentation primary detector for DeepStream 9.
onnx-file=../models/onnx/yolo11s-seg_cust_fused.onnx
model-engine-file=DS9/models/engines/yolo11s-seg_cust_fused.engine
labelfile-path=../models/coco_labels.txt

gpu-id=0
batch-size=3
interval=0
gie-unique-id=1
process-mode=1
network-type=3
network-mode=2
net-scale-factor=0.003921568627
model-color-format=0
maintain-aspect-ratio=0
symmetric-padding=0
cluster-mode=4

num-detected-classes=80
operate-on-class-ids=0

parse-bbox-instance-mask-func-name=NvDsInferParseYoloSeg
custom-lib-path=nvdsinfer_yolo11_seg/libnvdsinfer_yolo11_seg.so
output-instance-mask=1
output-blob-names=output0
segmentation-threshold=0.70
output-tensor-meta=0

[class-attrs-all]
pre-cluster-threshold=0.99
topk=300
nms-iou-threshold=0.45

[class-attrs-0]
pre-cluster-threshold=0.35
