uris:
  - camera-secret:living-room
  - camera-secret:kitchen
  - camera-secret:family-room
sensor_ids:
  - "0"
  - "1"
  - "2"
sensor_names:
  - Living Room Camera
  - Kitchen Camera
  - Family Room Camera
width: 1920
height: 1080
